import Head from 'next/head'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Indexbody from '../components/indexbody'

export default function Home() {

  return (
    <div className='home-page'>
      <Header />

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Indexbody />


      <Footer />

    </div>

  )
}
