import React from 'react'
import Head from 'next/head'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Kopabody from '../components/Kopabody'

const Kopa = () => {
  return (
    <div className='kopa-page'>
      <Header />

      <Head>
        <title>Vi köper LP-skivor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Kopabody />


      <Footer />

    </div>
  )
}

export default Kopa