import React from 'react'
import Head from 'next/head'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Saljbody from '../components/Saljbody'

const Salj = () => {
  return (
    <div className='container'>
      <Header />

      <Head>
        <title>Vi köper LP-skivor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Saljbody />


      <Footer />

    </div>
  )
}

export default Salj